// Package saucer is the plugin's worked example of *composing with the ecosystem*:
// a hand-authored subject — a cartoon flying saucer — drifting across a background
// night sky generated by the fresco provider, coupled so the two read as one scene.
//
// It exists to answer a fair criticism of the plugin — that it *documents* combining
// tools (references/tools.md) far more than it *demonstrates* it. The other examples
// (plasma, nebula, torus) are pure stdlib maths; this one imports
// github.com/ZviBaratz/fresco and builds on top of it, the way references/tools.md
// §"Providers" and SKILL.md §3 tell an author to.
//
// The design idea — what makes a *combine* read rather than a *stack*:
//
//   - A provider for the background, not a reimplementation. The aurora sky — its
//     flowing blue/pink light-curtains — is fresco's Render(w, h, tick, Aurora), not
//     maths rewritten here. That is the "don't rebuild rain / tunnel / ripple / galaxy"
//     rule (SKILL.md red flags) followed literally: reach for the provider. (An earlier
//     cut of this example used fresco's Galaxy field, which — being a smooth, subtle,
//     low-contrast subject — renders as mud in coarse glyphs. Aurora, a *directional*
//     field, reads beautifully; the subject was chosen to the medium, not against it.)
//   - A subject with character, chosen to the medium. A crisp, bold sprite is exactly
//     what a cell grid renders well — a silver disc, a cyan canopy, blinking underlights.
//     The eye gets something to *watch* (craft.md: coherent global motion reads as
//     intent), and the whimsy is the "one idea the generic version lacks" (SKILL.md §1).
//   - Coupling — the saucer belongs to the sky. It is not pasted on top: it *lights the
//     sky beneath it* (a soft glow halo), and on some passes lowers a translucent tractor
//     beam that the aurora and stars show through. The subject drives the field, made
//     literal (SKILL.md §3).
//   - Depth behind the subject. A sparse field of faint twinkling stars fills the dark
//     sky between the curtains, so the night has depth even when the saucer is away.
//   - Never a loop you can feel. Each pass is deterministically *varied* — a different
//     height, speed, direction, and whether it trails a beam — with long empty gaps
//     between, so the sky is mostly quiet and the flyby is an event.
//   - Determinism. fresco.Render is pure when its Profile is pinned (TrueColor here), and
//     every other layer takes animation only through tick and randomness only through an
//     integer coordinate hash (hash2) — never math/rand — so the saucer's whole timeline,
//     the stars' twinkle, and the beam are a pure function of (w, h, tick), and
//     snapshot-testable (see saucer_test.go).
//   - Free-running, not a seamless loop — like examples/plasma, unlike examples/nebula.
//     Time is linear, so it drifts forever but never *exactly* repeats; there is no seam
//     to pin, hence no TestLoopSeam. Ping-pong it for a seamless recording (README.md).
//
// The taste constants below were chosen against the beauty gate (the ansi2png.py
// filmstrip), by eye — not computed. See README.md.
package saucer

import (
	"math"
	"strconv"
	"strings"

	"github.com/ZviBaratz/fresco"
)

// Tunable taste constants — decided by looking, not arithmetic.
const (
	auroraDim   = 0.60 // how far the aurora recedes into a night-sky wash (1 = no dimming)
	auroraGamma = 1.28 // >1 deepens the sky between the curtains so stars and the saucer read

	starDensity     = 0.07  // fraction of cells that hold a star
	starThresh      = 0.24  // only show stars where the aurora is darker than this (empty sky)
	starBase        = 0.82  // a star's base brightness
	starTwinkleRate = 0.06  // how fast stars twinkle
	starSeed        = 90125 // decorrelates the star hash

	slot      = 540  // ticks per pass "slot" — one flyby then a long quiet gap
	crossMin  = 150  // fewest ticks a pass takes to cross (fastest saucer)
	crossMax  = 300  // most ticks a pass takes to cross (slowest, laziest saucer)
	bandTop   = 0.12 // highest the saucer flies (fraction of pane height)
	bandBot   = 0.52 // lowest it flies
	bobAmp    = 1.4  // vertical bob amplitude in cells
	bobCycles = 3.0  // how many bob cycles across one pass
	beamProb  = 0.5  // fraction of passes that lower a tractor beam
	passSeed  = 1947 // decorrelates the per-pass hash

	glowStr     = 0.34 // brightness the saucer's glow adds to the sky beneath it
	glowSpreadX = 62.0 // horizontal glow falloff (larger = wider)
	glowSpreadY = 20.0 // vertical glow falloff

	beamStr     = 0.5  // tractor-beam brightness at its source
	beamLen     = 15.0 // beam length in cells
	beamTopHalf = 1.5  // beam half-width at the saucer
	beamSpread  = 0.42 // how much the beam widens per cell of descent
	beamPulse   = 0.06 // beam shimmer rate

	blinkRate = 4 // ticks per underlight colour step

	vigPow = 0.32 // gentle edge vignette (small = barely there, keeps corner stars)
)

// skyPalette is the designed input to fresco's aurora: the tokyo-night gradient
// (warm pink → violet → blue → cyan, pale highlight). The cool curtains make a calm
// night sky, and the pale highlight gives the brightest folds a believable glow.
var skyPalette = fresco.Palette{
	A0:        "#f7768e",
	A1:        "#bb9af7",
	A2:        "#7aa2f7",
	A3:        "#7dcfff",
	Highlight: "#c0caf5",
}

// The saucer sprite, as a legend grid (space = transparent):
//
//	D = dome glass (cyan-white)   B = body highlight (bright silver)
//	M = hull (silver)             o/O = blinking underlights
//
// Width-1 glyphs only; the solid parts paint a full block so the disc reads as a
// crisp cartoon silhouette rather than an ASCII sketch (craft.md: bold reads in a grid).
var saucerSprite = []string{
	"    DDDDD    ",
	"  BBBBBBBBB  ",
	" MMMMMMMMMMM ",
	"  o O o O o  ",
}

var (
	spriteW = len([]rune(saucerSprite[0]))
	spriteH = len(saucerSprite)
)

type rgb struct{ r, g, b float64 }

// cell is one parsed background cell from fresco's aurora: the glyph fresco drew, its
// (undimmed) foreground colour, and whether fresco lit it at all. An unlit cell is
// empty sky (fresco emitted a plain space there).
type cell struct {
	ch      rune
	r, g, b uint8
	lit     bool
}

// parseSky renders the fresco aurora for this frame and decodes its ANSI back into a
// w×h grid of cells. fresco emits foreground-only truecolor glyphs — ESC[38;2;r;g;bm,
// then glyphs, then ESC[0m — with plain spaces for empty sky; this walks exactly that
// grammar, and tolerates anything it does not recognise by leaving the cell unlit, so
// the h×w grid is always fully populated regardless of what fresco returns.
//
// Rendering the provider to a string and parsing it back is the general shape of
// building on ANY terminal provider whose public surface is rendered output: decode to
// a cell grid, composite, re-emit (references/tools.md). fresco's grammar makes it cheap.
func parseSky(w, h, tick int) [][]cell {
	grid := make([][]cell, h)
	for r := range grid {
		grid[r] = make([]cell, w)
		for c := range grid[r] {
			grid[r][c] = cell{ch: ' '}
		}
	}

	// Profile pinned to TrueColor so Render is pure over its inputs (deterministic,
	// snapshot-testable), independent of the ambient terminal.
	s := fresco.Render(w, h, tick, fresco.Options{
		Palette:  skyPalette,
		Variant:  fresco.Aurora,
		FocalRow: -1,
		Profile:  fresco.TrueColor,
	})

	var cr, cg, cb uint8
	colorSet := false
	row, col := 0, 0
	for i := 0; i < len(s); {
		c := s[i]

		// CSI ... m — the only escape fresco emits. Parse its numeric params; act on
		// the two we care about (0 resets the colour, 38;2;r;g;b sets it) and ignore
		// the rest. Any non-'m' final byte is consumed so it cannot desync the columns.
		if c == 0x1b && i+1 < len(s) && s[i+1] == '[' {
			j := i + 2
			var params []int
			cur, hasDigit := 0, false
			for j < len(s) {
				d := s[j]
				if d >= '0' && d <= '9' {
					cur, hasDigit = cur*10+int(d-'0'), true
					j++
					continue
				}
				if d == ';' {
					params = append(params, cur)
					cur, hasDigit = 0, false
					j++
					continue
				}
				break
			}
			if hasDigit || len(params) > 0 {
				params = append(params, cur)
			}
			if j < len(s) && s[j] == 'm' {
				if len(params) == 0 || params[0] == 0 {
					colorSet = false
				} else if len(params) >= 5 && params[0] == 38 && params[1] == 2 {
					cr, cg, cb = clampByte(params[2]), clampByte(params[3]), clampByte(params[4])
					colorSet = true
				}
			}
			if j < len(s) {
				j++ // consume the final byte
			}
			i = j
			continue
		}

		if c == '\n' {
			row++
			col = 0
			i++
			continue
		}

		// One UTF-8 rune (fresco's glyphs are ≤3 bytes); place it as a cell.
		size := 1
		switch {
		case c >= 0xF0:
			size = 4
		case c >= 0xE0:
			size = 3
		case c >= 0xC0:
			size = 2
		}
		if i+size > len(s) {
			size = 1
		}
		ru := []rune(s[i : i+size])
		i += size
		if row < h && col < w && len(ru) > 0 {
			if colorSet && ru[0] != ' ' {
				grid[row][col] = cell{ch: ru[0], r: cr, g: cg, b: cb, lit: true}
			}
			// else: leave the default unlit space.
		}
		col++
	}
	return grid
}

// flight is the saucer's state at one tick: whether it is on screen this frame, its
// centre in cell coordinates, and whether this pass trails a tractor beam.
type flight struct {
	shown  bool
	cx, cy float64
	beam   bool
}

// flightAt is the saucer's whole timeline as a closed form of tick — the reason the
// animation stays a pure Frame. Time is cut into fixed `slot`-long passes; within each
// slot the saucer crosses once (over `cross` ticks, starting at `start`) and is absent
// the rest of the time, so the sky is mostly quiet and a flyby is an event. Every pass's
// character — direction, speed, height, bob, and whether it beams — is drawn from a hash
// of the pass index, so no two consecutive passes feel the same and it never reads as a
// loop. Both Frame and TestSaucerComesAndGoes call this, so the "occasional pass"
// behaviour is pinned by a test.
func flightAt(w, h, tick int) flight {
	if tick < 0 {
		tick = -tick
	}
	idx := uint32(tick / slot)
	local := tick % slot

	cross := crossMin + int(float64(crossMax-crossMin)*hash2(idx, 0, passSeed))
	// Start within the slot but leave a gap afterwards, so `shown` is always false for
	// part of every slot (the quiet sky the flyby punctuates).
	start := int(float64(slot-cross) * 0.7 * hash2(idx, 0, passSeed+1))
	if local < start || local >= start+cross {
		return flight{shown: false}
	}

	p := float64(local-start) / float64(cross) // 0..1 progress across the sky
	margin := float64(spriteW)/2 + 3
	span := float64(w) + 2*margin
	var cx float64
	if hash2(idx, 0, passSeed+2) < 0.5 { // direction: left→right or right→left
		cx = -margin + p*span
	} else {
		cx = float64(w) + margin - p*span
	}

	yb := lerp(bandTop, bandBot, hash2(idx, 0, passSeed+3))
	cy := yb*float64(h) + bobAmp*math.Sin(p*math.Pi*bobCycles+hash2(idx, 0, passSeed+4)*2*math.Pi)

	return flight{shown: true, cx: cx, cy: cy, beam: hash2(idx, 0, passSeed+5) < beamProb}
}

// isStar reports whether cell (c, r) holds a star, and its twinkling brightness. The
// star lattice is fixed (a coordinate hash); only the twinkle moves with t. Stars are
// painted by Frame only where the aurora is dark, so they fill the empty night rather
// than fighting the curtains.
func isStar(c, r int, t float64) (float64, bool) {
	if hash2(uint32(int32(c)), uint32(int32(r)), starSeed) >= starDensity {
		return 0, false
	}
	phase := hash2(uint32(int32(c)), uint32(int32(r)), starSeed+1) * 2 * math.Pi
	tw := 0.55 + 0.45*math.Sin(starTwinkleRate*t+phase)
	amp := 0.7 + 0.3*hash2(uint32(int32(c)), uint32(int32(r)), starSeed+2)
	return starBase * amp * tw, true
}

// spritePixel returns the colour and glyph of the saucer at sprite-local (sr, sc), or
// ok=false for a transparent cell. The underlights blink through a warm cycle keyed to
// tick and column, so the disc reads as a lit, moving craft.
func spritePixel(sr, sc, tick int) (rgb, rune, bool) {
	if sr < 0 || sr >= spriteH {
		return rgb{}, ' ', false
	}
	row := []rune(saucerSprite[sr])
	if sc < 0 || sc >= len(row) {
		return rgb{}, ' ', false
	}
	switch row[sc] {
	case 'D': // dome glass
		return rgb{0.80, 0.94, 1.00}, '█', true
	case 'B': // body highlight — the brightest band, catches the sky's light
		return rgb{0.90, 0.93, 1.00}, '█', true
	case 'M': // hull
		return rgb{0.70, 0.76, 0.90}, '█', true
	case 'o', 'O': // blinking underlights: red → amber → green
		switch ((tick / blinkRate) + sc) % 3 {
		case 0:
			return rgb{1.00, 0.42, 0.36}, '●', true
		case 1:
			return rgb{1.00, 0.84, 0.32}, '●', true
		default:
			return rgb{0.48, 1.00, 0.60}, '●', true
		}
	}
	return rgb{}, ' ', false
}

// beamAt is the tractor beam's additive contribution at cell (c, r): a translucent cone
// widening downward from the saucer's underside, brightest at the source and fading out,
// with a gentle shimmer. Zero outside the cone (or when this pass has no beam). Because
// it is additive, the sky and stars show through it.
func beamAt(fl flight, c, r int, t float64) rgb {
	if !fl.beam {
		return rgb{}
	}
	top := fl.cy + float64(spriteH)/2
	dy := float64(r) - top
	if dy <= 0 || dy >= beamLen {
		return rgb{}
	}
	half := beamTopHalf + dy*beamSpread
	dx := float64(c) - fl.cx
	if math.Abs(dx) >= half {
		return rgb{}
	}
	fall := (1 - dy/beamLen) * (1 - math.Abs(dx)/half)
	pulse := 0.8 + 0.2*math.Sin(beamPulse*t)
	e := beamStr * fall * fall * pulse
	return rgb{0.45 * e, 0.95 * e, 0.70 * e} // pale green-cyan
}

// vig is a gentle edge vignette so the night meets the border softly instead of as a
// hard box. Kept weak (vigPow) so corner stars survive.
func vig(u, yn float64) float64 {
	e := math.Sin(math.Pi*u) * math.Sin(math.Pi*yn)
	if e <= 0 {
		return 0
	}
	return math.Pow(e, vigPow)
}

// luma is Rec. 709 relative luminance of a [0,1] colour — used to ask "is the sky dark
// enough here to show a star?" and to pick a glyph for a light-only cell.
func luma(c rgb) float64 { return 0.2126*c.r + 0.7152*c.g + 0.0722*c.b }

// skyGlyphs is the ramp for a cell lit only by diffuse light (glow or beam) with no
// aurora glyph and no star of its own — so that light still reads as a soft mark.
var skyGlyphs = []rune{'.', ':', '+', '*'}

// Frame renders frame `tick` into exactly h lines of exactly w visible cells (or "" for
// a degenerate pane). The background is fresco's aurora, dimmed and deepened into a night
// sky with twinkling stars; over it drifts the saucer, lighting the sky beneath it and,
// on some passes, trailing a tractor beam. Pure in (w, h, tick).
func Frame(w, h, tick int) string {
	if w <= 0 || h <= 0 {
		return ""
	}
	grid := parseSky(w, h, tick)
	fl := flightAt(w, h, tick)
	t := float64(tick)
	W, H := float64(w), float64(h)

	// Sprite bounding box for this frame (only stamp cells inside it).
	left := int(math.Round(fl.cx)) - spriteW/2
	topRow := int(math.Round(fl.cy)) - spriteH/2

	var b strings.Builder
	b.Grow(w*h*22 + h*5)
	for r := 0; r < h; r++ {
		yn := (float64(r) + 0.5) / H
		var lr, lg, lb uint8
		colorSet := false
		for c := 0; c < w; c++ {
			u := (float64(c) + 0.5) / W
			bg := grid[r][c]

			var out rgb
			glyph := ' '
			lit := false

			// 1. Saucer sprite — opaque, drawn over everything.
			if fl.shown {
				if col, g, ok := spritePixel(r-topRow, c-left, tick); ok {
					out, glyph, lit = col, g, true
				}
			}

			if !lit {
				// 2. The night sky: aurora, dimmed and deepened.
				var field rgb
				var fieldLum float64
				if bg.lit {
					field = rgb{float64(bg.r) / 255, float64(bg.g) / 255, float64(bg.b) / 255}
					fieldLum = luma(field)
				}
				dim := auroraDim * math.Pow(fieldLum, auroraGamma-1) // deepen the darks
				out = rgb{field.r * dim, field.g * dim, field.b * dim}
				if bg.lit {
					glyph = bg.ch
					lit = true
				}

				// 3. A star, only in dark sky (so stars fill the gaps, not the curtains).
				if fieldLum < starThresh {
					if s, ok := isStar(c, r, t); ok {
						out = rgb{out.r + 0.80*s, out.g + 0.85*s, out.b + 1.00*s}
						glyph = starGlyph(s)
						lit = true
					}
				}

				// 4. The saucer's contributions to the sky: a glow halo, and a beam.
				if fl.shown {
					dx := float64(c) - fl.cx
					dy := float64(r) - (fl.cy + float64(spriteH)/2)
					gl := glowStr * math.Exp(-(dx*dx/glowSpreadX + dy*dy/glowSpreadY))
					be := beamAt(fl, c, r, t)
					if gl > 0.004 || be.r+be.g+be.b > 0 {
						out = rgb{
							out.r + 0.55*gl + be.r,
							out.g + 0.70*gl + be.g,
							out.b + 0.60*gl + be.b,
						}
						if !lit {
							glyph = skyGlyph(luma(out))
							lit = true
						}
					}
				}
			}

			// Gentle vignette on the final composite.
			v := vig(u, yn)
			out = rgb{out.r * v, out.g * v, out.b * v}

			if lit && (out.r > 0 || out.g > 0 || out.b > 0) {
				R, G, B := chan8(out.r), chan8(out.g), chan8(out.b)
				if !colorSet || R != lr || G != lg || B != lb {
					appendFG(&b, R, G, B)
					lr, lg, lb, colorSet = R, G, B, true
				}
				b.WriteRune(glyph)
			} else {
				if colorSet {
					b.WriteString("\x1b[0m")
					colorSet = false
				}
				b.WriteByte(' ')
			}
		}
		if colorSet {
			b.WriteString("\x1b[0m")
		}
		if r < h-1 {
			b.WriteByte('\n')
		}
	}
	return b.String()
}

// starGlyph picks a glyph for a star by its brightness — a faint one is a dot, a bright
// twinkle a small cross.
func starGlyph(s float64) rune {
	switch {
	case s > 0.7:
		return '+'
	case s > 0.4:
		return '·'
	default:
		return '.'
	}
}

// skyGlyph picks a glyph for a cell lit only by diffuse light (glow/beam) by luminance.
func skyGlyph(l float64) rune {
	idx := int(clamp01(l*1.6) * float64(len(skyGlyphs)))
	if idx >= len(skyGlyphs) {
		idx = len(skyGlyphs) - 1
	}
	return skyGlyphs[idx]
}

// appendFG writes a truecolor foreground SGR. Hand-rolled with strconv so the per-cell
// hot path carries no fmt reflection or allocation.
func appendFG(b *strings.Builder, r, g, bl uint8) {
	b.WriteString("\x1b[38;2;")
	writeChan(b, r)
	b.WriteByte(';')
	writeChan(b, g)
	b.WriteByte(';')
	writeChan(b, bl)
	b.WriteByte('m')
}

// writeChan appends one colour channel's decimal digits (0–255) to b.
func writeChan(b *strings.Builder, v uint8) {
	var s [3]byte
	b.Write(strconv.AppendUint(s[:0], uint64(v), 10))
}

// hash2 is the deterministic randomness source: a uint32 bit-mix of an integer lattice
// coordinate + seed, in [0,1). Large odd primes decorrelate the axes; unsigned
// multiplication wraps, which is what makes it a hash. (Same mixer as examples/nebula.)
func hash2(ix, iy, seed uint32) float64 {
	n := ix*374761393 + iy*668265263 + seed*2246822519
	n = (n ^ (n >> 13)) * 1274126177
	n ^= n >> 16
	return float64(n) / 4294967296.0
}

func lerp(a, b, t float64) float64 { return a + (b-a)*t }

func clamp01(x float64) float64 {
	switch {
	case x < 0:
		return 0
	case x > 1:
		return 1
	default:
		return x
	}
}

// clampByte narrows a parsed SGR channel to a byte, defending the parser against a
// malformed sequence without letting it panic.
func clampByte(v int) uint8 {
	switch {
	case v < 0:
		return 0
	case v > 255:
		return 255
	default:
		return uint8(v)
	}
}

func chan8(x float64) uint8 {
	switch {
	case x <= 0:
		return 0
	case x >= 1:
		return 255
	default:
		return uint8(x*255 + 0.5)
	}
}
