// Package embers is the plugin's worked example of *composing with the
// ecosystem*: a foreground effect of this repo's own, layered over a background
// field generated by the fresco provider, coupled so the two read as one scene.
//
// It exists to answer a fair criticism of the plugin — that it *documents*
// combining tools (references/tools.md) far more than it *demonstrates* it. The
// other examples (plasma, nebula, torus) are pure stdlib maths; this one imports
// github.com/ZviBaratz/fresco and builds on top of it, the way references/tools.md
// §"Providers" and SKILL.md §3 tell an author to. Composed past the conventional
// "one effect in flat ASCII" default:
//
//   - A provider for the background, not a reimplementation. The galaxy — its
//     bulge, spiral arms, dust lane, warm-core/cool-rim palette — is fresco's
//     Render(w, h, tick, Galaxy), not maths rewritten here. That is the
//     "don't rebuild rain / tunnel / ripple / galaxy" rule (SKILL.md red flags)
//     followed literally: reach for the provider.
//   - Layering with intent. The galaxy is *dimmed* into a recessed wash (frescoDim)
//     so it sits behind, then a sparse drift of warm embers is composited in front.
//     A slow field wash behind a foreground of particles, tied by a focal vignette,
//     is exactly the "layer" move from SKILL.md §3.
//   - Coupling — the one idea a generic "field + particles" lacks. An ember does not
//     just sit on top of the galaxy; it *catches its light*. Where an ember crosses a
//     bright arm it flares (its brightness is lifted by the field luminance beneath —
//     glowCouple) and takes on a tint of the arm's colour (hueCouple), so the two
//     layers are driven by each other rather than merely stacked. "Drive one effect
//     with another" (SKILL.md §3), made literal.
//   - Fidelity tier — kept as fresco's. fresco paints one truecolor glyph per cell
//     (its density ramp ·:+=*oO0 IS a second brightness channel), and its output is
//     one colour per cell, with no sub-cell detail to promote to half-blocks. So this
//     example stays in the glyph+foreground-colour tier and composites there, rather
//     than fighting the provider's model. The climb past the default here is the
//     *composition*, not the spatial rung.
//   - Determinism. fresco.Render is pure when its Profile is pinned (TrueColor here),
//     and the ember layer takes animation only through tick and randomness only through
//     an integer coordinate hash (hash2) — never math/rand — so the whole composite is
//     a pure function of (w, h, tick) and snapshot-testable (see embers_test.go).
//   - Free-running, not a seamless loop — like examples/plasma, unlike examples/nebula.
//     Time is linear (the galaxy advances by tick; the ember field scrolls by tick), so
//     it drifts forever but never *exactly* repeats. There is no seam to pin, hence no
//     TestLoopSeam; ping-pong it for a seamless recording (see README.md).
//
// The taste constants below were chosen against the beauty gate (the ansi2png.py
// filmstrip), by eye — not computed. See README.md.
package embers

import (
	"math"
	"strconv"
	"strings"

	"github.com/ZviBaratz/fresco"
)

// Tunable taste constants — decided by looking, not arithmetic.
const (
	frescoDim = 0.60 // how far the galaxy recedes behind the embers (1 = no dimming)

	emberBase  = 0.85 // an ember's own light, before the field lifts it
	glowCouple = 0.75 // how much the field's luminance beneath lifts an ember's brightness
	hueCouple  = 0.22 // how much an ember takes on the tint of the arm it crosses

	emberScale    = 0.5   // ember lattice frequency vs. cells
	emberDensity  = 0.085 // fraction of lattice cells that hold an ember
	emberRadius   = 1.6   // ember glow radius in cells
	emberRise     = 0.055 // cells/tick the ember field scrolls upward (the drift)
	emberSway     = 0.8   // horizontal sway amplitude in cells
	emberSwayFreq = 0.25  // vertical frequency of the sway
	emberSwayRate = 0.045 // sway speed over time
	emberTwinkleK = 0.16  // per-ember twinkle rate
	emberCut      = 0.14  // below this an ember is invisible — keeps them sparse and punchy

	vigPow = 0.48 // vignette softness (smaller = softer, larger bright core)

	emberSeed = 20261 // decorrelates the ember hash
)

// galaxyPalette is the designed input to fresco's field: the tokyo-night gradient
// (warm pink → violet → blue → cyan, pale highlight). Chosen for the composition —
// the arms run cool (blue/cyan) so the warm embers pop against them, while the warm
// core harmonises with the ember colour rather than fighting it.
var galaxyPalette = fresco.Palette{
	A0:        "#f7768e",
	A1:        "#bb9af7",
	A2:        "#7aa2f7",
	A3:        "#7dcfff",
	Highlight: "#c0caf5",
}

// An ember runs from a deep orange when faint to a gold-white when hot — a real ember
// has a white-hot core, and (as the beauty gate showed) a merely-dark-amber dot renders
// as almost nothing once ansi2png weighs it by the glyph's small ink coverage. emberCool
// is a faint ember's colour; emberHot is a bright one's core. hueCouple then tints this
// toward the arm the ember crosses.
var (
	emberCool = rgb{0.98, 0.48, 0.15}
	emberHot  = rgb{1.00, 0.95, 0.82}
)

// emberGlyphs is the foreground density ramp, dim → bright. Width-1 ASCII, so a lit
// cell is always exactly one visible column (the width-1-safe pixel, SKILL.md). The
// brighter glyphs carry more ink, so a hot ember reads as a fuller mark, not just a
// warmer colour — brightness rides both channels (glyph coverage and colour), the
// two-channel split craft.md asks for.
var emberGlyphs = []rune{'.', ':', '+', '*', '#'}

type rgb struct{ r, g, b float64 }

// cell is one parsed background cell from fresco's field: the glyph fresco drew, its
// (undimmed) foreground colour, and whether fresco lit it at all. An unlit cell is
// empty sky (fresco emitted a plain space there).
type cell struct {
	ch      rune
	r, g, b uint8
	lit     bool
}

// parseField renders the fresco galaxy for this frame and decodes its ANSI back into
// a w×h grid of cells. fresco emits foreground-only truecolor glyphs — ESC[38;2;r;g;bm,
// then glyphs, then ESC[0m — with plain spaces for empty sky; this walks exactly that
// grammar, and tolerates anything it does not recognise by leaving the cell unlit, so
// the h×w grid is always fully populated regardless of what fresco returns.
//
// Rendering the provider to a string and parsing it back is the general shape of
// building on ANY terminal provider whose public surface is rendered output: decode to
// a cell grid, composite, re-emit (references/tools.md). fresco's grammar makes it cheap.
func parseField(w, h, tick int) [][]cell {
	grid := make([][]cell, h)
	for r := range grid {
		grid[r] = make([]cell, w)
		for c := range grid[r] {
			grid[r][c] = cell{ch: ' '}
		}
	}

	// Profile pinned to TrueColor so Render is pure over its inputs (deterministic,
	// snapshot-testable), independent of the ambient terminal. FocalRow -1 centres
	// the galaxy on the pane.
	s := fresco.Render(w, h, tick, fresco.Options{
		Palette:  galaxyPalette,
		Variant:  fresco.Galaxy,
		FocalRow: -1,
		Profile:  fresco.TrueColor,
	})

	var cr, cg, cb uint8
	colorSet := false
	row, col := 0, 0
	for i := 0; i < len(s); {
		c := s[i]

		// CSI ... m — the only escape fresco emits. Parse its numeric params; act on
		// the two we care about (0 resets the colour, 38;2;r;g;b sets it) and ignore
		// the rest. Any non-'m' final byte is consumed so it cannot desync the columns.
		if c == 0x1b && i+1 < len(s) && s[i+1] == '[' {
			j := i + 2
			var params []int
			cur, hasDigit := 0, false
			for j < len(s) {
				d := s[j]
				if d >= '0' && d <= '9' {
					cur, hasDigit = cur*10+int(d-'0'), true
					j++
					continue
				}
				if d == ';' {
					params = append(params, cur)
					cur, hasDigit = 0, false
					j++
					continue
				}
				break
			}
			if hasDigit || len(params) > 0 {
				params = append(params, cur)
			}
			if j < len(s) && s[j] == 'm' {
				if len(params) == 0 || params[0] == 0 {
					colorSet = false
				} else if len(params) >= 5 && params[0] == 38 && params[1] == 2 {
					cr, cg, cb = clampByte(params[2]), clampByte(params[3]), clampByte(params[4])
					colorSet = true
				}
			}
			if j < len(s) {
				j++ // consume the final byte
			}
			i = j
			continue
		}

		if c == '\n' {
			row++
			col = 0
			i++
			continue
		}

		// One UTF-8 rune (fresco's glyphs are ≤3 bytes); place it as a cell.
		size := 1
		switch {
		case c >= 0xF0:
			size = 4
		case c >= 0xE0:
			size = 3
		case c >= 0xC0:
			size = 2
		}
		if i+size > len(s) {
			size = 1
		}
		ru := []rune(s[i : i+size])
		i += size
		if row < h && col < w && len(ru) > 0 {
			if colorSet && ru[0] != ' ' {
				grid[row][col] = cell{ch: ru[0], r: cr, g: cg, b: cb, lit: true}
			}
			// else: leave the default unlit space.
		}
		col++
	}
	return grid
}

// emberReach is how many lattice cells out emberLum must search: an ember's glow spans
// emberRadius, so a mote up to ceil(emberRadius) cells away can still reach the sample.
// Deriving it from the radius keeps the two in step if emberRadius is retuned.
var emberReach = int(math.Ceil(emberRadius))

// emberLum is the foreground layer's brightness at cell (col, py) and time t: the soft,
// twinkling contribution of the nearest seeded ember. The ember lattice is static; the
// whole sample coordinate scrolls upward (t*emberRise) and sways (a smooth function of
// height and time), so the motes read as a slow warm drift. Pure in (col, py, t) — all
// randomness enters through the integer hash. 0 means no ember here.
func emberLum(col, py int, t float64) float64 {
	wx := float64(col) * emberScale
	wy := float64(py)*emberScale + t*emberRise
	wx += emberSway * math.Sin(wy*emberSwayFreq+t*emberSwayRate)

	bx, by := math.Floor(wx), math.Floor(wy)
	best := 0.0
	for dj := -emberReach; dj <= emberReach; dj++ {
		for di := -emberReach; di <= emberReach; di++ {
			cx, cy := bx+float64(di), by+float64(dj)
			ix, iy := uint32(int32(cx)), uint32(int32(cy))
			if hash2(ix, iy, emberSeed) >= emberDensity {
				continue
			}
			sx := cx + hash2(ix, iy, emberSeed+1)
			sy := cy + hash2(ix, iy, emberSeed+2)
			d := math.Hypot(wx-sx, wy-sy)
			if d >= emberRadius {
				continue
			}
			base := 0.5 + 0.5*hash2(ix, iy, emberSeed+3)
			phase := hash2(ix, iy, emberSeed+4) * 2 * math.Pi
			twinkle := 0.6 + 0.4*math.Sin(emberTwinkleK*t+phase)
			fall := 1 - d/emberRadius
			if l := base * twinkle * fall * fall; l > best {
				best = l
			}
		}
	}
	return best
}

// vig is the edge vignette: 1 at the centre, fading to 0 at every border, so the scene
// reads as a window onto something larger rather than a lit box. Applied to both layers
// so it ties them to one focal centre.
func vig(u, yn float64) float64 {
	e := math.Sin(math.Pi*u) * math.Sin(math.Pi*yn)
	if e <= 0 {
		return 0
	}
	return math.Pow(e, vigPow)
}

// luma is Rec. 709 relative luminance of a linearised-enough [0,1] colour — good enough
// to ask "how bright is the arm under this ember?" for the glow coupling.
func luma(c rgb) float64 { return 0.2126*c.r + 0.7152*c.g + 0.0722*c.b }

// Frame renders frame `tick` into exactly h lines of exactly w visible cells (or "" for
// a degenerate pane). Each lit cell is one truecolor foreground glyph; empty sky is a
// plain space. The background is fresco's galaxy, dimmed; the foreground is the ember
// drift, additively composited and coupled to the field beneath. Pure in (w, h, tick).
func Frame(w, h, tick int) string {
	if w <= 0 || h <= 0 {
		return ""
	}
	grid := parseField(w, h, tick)
	t := float64(tick)
	W, H := float64(w), float64(h)

	var b strings.Builder
	// A lit cell is at most ~22 bytes (\x1b[38;2;255;255;255m + glyph); each row adds a
	// 4-byte reset and a newline.
	b.Grow(w*h*22 + h*5)
	for r := 0; r < h; r++ {
		yn := (float64(r) + 0.5) / H
		var lr, lg, lb uint8
		colorSet := false
		for c := 0; c < w; c++ {
			u := (float64(c) + 0.5) / W
			bg := grid[r][c]

			// The galaxy beneath, undimmed (for coupling) and dimmed (for painting).
			var field rgb
			var fieldLum float64
			if bg.lit {
				field = rgb{float64(bg.r) / 255, float64(bg.g) / 255, float64(bg.b) / 255}
				fieldLum = luma(field)
			}

			em := emberLum(c, r, t)

			var out rgb
			glyph := ' '
			lit := false
			switch {
			case em > emberCut:
				e := (em - emberCut) / (1 - emberCut)
				// The ember catches the field's light: it burns brighter over a bright
				// arm (fieldLum lifts it past its own emberBase). bright saturates at 1,
				// its core colour, while glow keeps the extra so a hot ember reaches the
				// fullest glyph.
				glow := e * (emberBase + glowCouple*fieldLum)
				bright := clamp01(glow)
				// Cool→hot core by brightness (a hot ember goes gold-white), then tinted
				// toward the arm's colour where one is present.
				ec := rgb{
					lerp(emberCool.r, emberHot.r, bright),
					lerp(emberCool.g, emberHot.g, bright),
					lerp(emberCool.b, emberHot.b, bright),
				}
				if bg.lit {
					ec = rgb{
						lerp(ec.r, field.r, hueCouple),
						lerp(ec.g, field.g, hueCouple),
						lerp(ec.b, field.b, hueCouple),
					}
				}
				// Additive over the dimmed field, so the ember glows through it. The core
				// keeps a floor of brightness (0.55+…) so even a faint mote is a visible
				// point of light rather than a near-black dot.
				amp := 0.55 + 0.45*bright
				out = rgb{
					field.r*frescoDim + ec.r*amp,
					field.g*frescoDim + ec.g*amp,
					field.b*frescoDim + ec.b*amp,
				}
				glyph = emberGlyph(glow)
				lit = true
			case bg.lit:
				out = rgb{field.r * frescoDim, field.g * frescoDim, field.b * frescoDim}
				glyph = bg.ch
				lit = true
			}

			// Focal vignette on the final composite.
			v := vig(u, yn)
			out = rgb{out.r * v, out.g * v, out.b * v}

			if lit {
				R, G, B := chan8(out.r), chan8(out.g), chan8(out.b)
				if !colorSet || R != lr || G != lg || B != lb {
					appendFG(&b, R, G, B)
					lr, lg, lb, colorSet = R, G, B, true
				}
				b.WriteRune(glyph)
			} else {
				if colorSet {
					b.WriteString("\x1b[0m")
					colorSet = false
				}
				b.WriteByte(' ')
			}
		}
		if colorSet {
			b.WriteString("\x1b[0m")
		}
		if r < h-1 {
			b.WriteByte('\n')
		}
	}
	return b.String()
}

// emberGlyph picks the foreground glyph for an ember of the given brightness — a small
// density ramp so a faint mote reads as a dot and a bright one as a star.
func emberGlyph(glow float64) rune {
	idx := int(clamp01(glow) * float64(len(emberGlyphs)))
	if idx >= len(emberGlyphs) {
		idx = len(emberGlyphs) - 1
	}
	return emberGlyphs[idx]
}

// appendFG writes a truecolor foreground SGR. Hand-rolled with strconv so the per-cell
// hot path carries no fmt reflection or allocation.
func appendFG(b *strings.Builder, r, g, bl uint8) {
	b.WriteString("\x1b[38;2;")
	writeChan(b, r)
	b.WriteByte(';')
	writeChan(b, g)
	b.WriteByte(';')
	writeChan(b, bl)
	b.WriteByte('m')
}

// writeChan appends one colour channel's decimal digits (0–255) to b.
func writeChan(b *strings.Builder, v uint8) {
	var s [3]byte
	b.Write(strconv.AppendUint(s[:0], uint64(v), 10))
}

// hash2 is the deterministic randomness source: a uint32 bit-mix of an integer lattice
// coordinate + seed, in [0,1). Large odd primes decorrelate the axes; unsigned
// multiplication wraps, which is what makes it a hash. (Same mixer as examples/nebula.)
func hash2(ix, iy, seed uint32) float64 {
	n := ix*374761393 + iy*668265263 + seed*2246822519
	n = (n ^ (n >> 13)) * 1274126177
	n ^= n >> 16
	return float64(n) / 4294967296.0
}

func lerp(a, b, t float64) float64 { return a + (b-a)*t }

func clamp01(x float64) float64 {
	switch {
	case x < 0:
		return 0
	case x > 1:
		return 1
	default:
		return x
	}
}

// clampByte narrows a parsed SGR channel to a byte, defending the parser against a
// malformed sequence without letting it panic.
func clampByte(v int) uint8 {
	switch {
	case v < 0:
		return 0
	case v > 255:
		return 255
	default:
		return uint8(v)
	}
}

func chan8(x float64) uint8 {
	switch {
	case x <= 0:
		return 0
	case x >= 1:
		return 255
	default:
		return uint8(x*255 + 0.5)
	}
}
