// Package embers is the plugin's worked example of *composing with the
// ecosystem*: a foreground effect of this repo's own, layered over a background
// field generated by the fresco provider — and coupled so hard that the two read
// as one lit scene, not two stacked layers.
//
// It exists to answer a fair criticism of the plugin — that it *documents*
// combining tools (references/tools.md) far more than it *demonstrates* it. The
// other examples (plasma, nebula, torus) are pure stdlib maths; this one imports
// github.com/ZviBaratz/fresco and builds on top of it, the way references/tools.md
// §"Providers" and SKILL.md §3 tell an author to.
//
// The design idea — the one thing that turns a stack into a scene: **the sparks
// belong to the galaxy.** They are not an independent effect drifting past it.
//
//   - A provider for the background, not a reimplementation. The galaxy — its
//     bulge, spiral arms, dust lane, warm-core/cool-rim palette — is fresco's
//     Render(w, h, tick, Galaxy), not maths rewritten here. That is the
//     "don't rebuild rain / tunnel / ripple / galaxy" rule (SKILL.md red flags)
//     followed literally: reach for the provider.
//   - Existence gated on the field — the structural coupling. A spark can only
//     exist where the galaxy is bright beneath it (fieldGate): the bright arms
//     shed sparks, the dark dust and the empty void shed none. Because the arms
//     rotate, the sparks inherit that motion for free — no independent second
//     drift to fight it (the earlier cut scattered sparks over the whole pane,
//     including the black corners, coupled to nothing; craft.md: "motion with no
//     origin reads as noise").
//   - Shed from the core — one shared origin. The luminance-weighted centroid of
//     the lit field is the real galactic core; the spark lattice drifts radially
//     *outward* from it (emberRise), so a spark is born bright near the core and
//     fades as it streams out along an arm — craft.md's "bright leading edge with
//     a decaying trail", and a single focal point both layers emanate from.
//   - Colour that reads the field's own gradient. A spark near the hot core burns
//     gold-white (emberHot); one far out on a cool arm stays deep orange
//     (emberCool). That is the galaxy's warm-core→cool-rim story retold in the
//     foreground, legible at a glance — not the earlier sub-perceptual 22% tint.
//   - Fidelity tier — kept as fresco's. fresco paints one truecolor glyph per cell
//     (its density ramp ·:+=*oO0 IS a second brightness channel), one colour per
//     cell, no sub-cell detail to promote to half-blocks. So this example
//     composites in the glyph+foreground-colour tier rather than fighting the
//     provider's model. The climb past the default here is the *composition*.
//   - Determinism. fresco.Render is pure when its Profile is pinned (TrueColor
//     here), and the ember layer takes animation only through tick and randomness
//     only through an integer coordinate hash (hash2) — never math/rand — so the
//     whole composite is a pure function of (w, h, tick) and snapshot-testable.
//   - Free-running, not a seamless loop — like examples/plasma, unlike
//     examples/nebula. Time is linear, so it drifts forever but never *exactly*
//     repeats; there is no seam to pin, hence no TestLoopSeam. Ping-pong it for a
//     seamless recording (see README.md).
//
// The taste constants below were chosen against the beauty gate (the ansi2png.py
// filmstrip), by eye — not computed. See README.md.
package embers

import (
	"math"
	"strconv"
	"strings"

	"github.com/ZviBaratz/fresco"
)

// Tunable taste constants — decided by looking, not arithmetic.
const (
	frescoDim  = 0.72 // how far the galaxy recedes behind the sparks (1 = no dimming)
	fieldGamma = 1.35 // >1 deepens the dust toward black so the bright arms read against it

	// The field gate — the coupling. A spark's intensity is multiplied by this
	// function of the galaxy luminance beneath it, so a spark only lives on a lit
	// arm and none survive over the dark void. gateFloor is the luminance below
	// which no spark exists at all; gateHi the luminance at which the gate is fully
	// open; gateGamma shapes the ramp between.
	gateFloor = 0.16
	gateHi    = 0.55
	gateGamma = 1.1

	emberScale   = 0.5  // spark lattice frequency vs. cells
	emberDensity = 0.19 // fraction of lattice cells that hold a mote (raised: the gate removes most)
	emberRadius  = 1.6  // spark glow radius in cells
	emberRise    = 0.05 // cells/tick the lattice drifts radially outward from the core (the shed)
	emberCut     = 0.11 // below this a spark is invisible — keeps them sparse and punchy

	coreBoost = 1.0  // extra brightness for sparks near the hot core
	ampFloor  = 0.58 // brightness floor so even a faint spark is a visible point of light

	vigPow = 0.5 // vignette softness (smaller = softer, larger bright core)

	emberSeed = 20261 // decorrelates the ember hash
)

// galaxyPalette is the designed input to fresco's field: the tokyo-night gradient
// (warm pink → violet → blue → cyan, pale highlight). Chosen for the composition —
// the arms run cool (blue/cyan) so the warm sparks pop against them, while the warm
// core harmonises with the spark colour rather than fighting it.
var galaxyPalette = fresco.Palette{
	A0:        "#f7768e",
	A1:        "#bb9af7",
	A2:        "#7aa2f7",
	A3:        "#7dcfff",
	Highlight: "#c0caf5",
}

// A spark runs from a deep orange when it is far out on a cool arm to a gold-white
// at the hot core — a real ember has a white-hot centre, and (as the beauty gate
// showed) a merely-dark-amber dot renders as almost nothing once ansi2png weighs it
// by the glyph's small ink coverage. emberCool is an outer spark's colour; emberHot
// is a core spark's. Core proximity mixes between them (see Frame).
var (
	emberCool = rgb{0.98, 0.48, 0.15}
	emberHot  = rgb{1.00, 0.95, 0.82}
)

// emberGlyphs is the foreground density ramp, dim → bright. Width-1 ASCII, so a lit
// cell is always exactly one visible column (the width-1-safe pixel, SKILL.md). The
// brighter glyphs carry more ink, so a hot spark reads as a fuller mark, not just a
// warmer colour — brightness rides both channels (glyph coverage and colour), the
// two-channel split craft.md asks for.
var emberGlyphs = []rune{'.', ':', '+', '*', '#'}

type rgb struct{ r, g, b float64 }

// cell is one parsed background cell from fresco's field: the glyph fresco drew, its
// (undimmed) foreground colour, and whether fresco lit it at all. An unlit cell is
// empty sky (fresco emitted a plain space there).
type cell struct {
	ch      rune
	r, g, b uint8
	lit     bool
}

// parseField renders the fresco galaxy for this frame and decodes its ANSI back into
// a w×h grid of cells. fresco emits foreground-only truecolor glyphs — ESC[38;2;r;g;bm,
// then glyphs, then ESC[0m — with plain spaces for empty sky; this walks exactly that
// grammar, and tolerates anything it does not recognise by leaving the cell unlit, so
// the h×w grid is always fully populated regardless of what fresco returns.
//
// Rendering the provider to a string and parsing it back is the general shape of
// building on ANY terminal provider whose public surface is rendered output: decode to
// a cell grid, composite, re-emit (references/tools.md). fresco's grammar makes it cheap.
func parseField(w, h, tick int) [][]cell {
	grid := make([][]cell, h)
	for r := range grid {
		grid[r] = make([]cell, w)
		for c := range grid[r] {
			grid[r][c] = cell{ch: ' '}
		}
	}

	// Profile pinned to TrueColor so Render is pure over its inputs (deterministic,
	// snapshot-testable), independent of the ambient terminal. FocalRow -1 centres
	// the galaxy on the pane.
	s := fresco.Render(w, h, tick, fresco.Options{
		Palette:  galaxyPalette,
		Variant:  fresco.Galaxy,
		FocalRow: -1,
		Profile:  fresco.TrueColor,
	})

	var cr, cg, cb uint8
	colorSet := false
	row, col := 0, 0
	for i := 0; i < len(s); {
		c := s[i]

		// CSI ... m — the only escape fresco emits. Parse its numeric params; act on
		// the two we care about (0 resets the colour, 38;2;r;g;b sets it) and ignore
		// the rest. Any non-'m' final byte is consumed so it cannot desync the columns.
		if c == 0x1b && i+1 < len(s) && s[i+1] == '[' {
			j := i + 2
			var params []int
			cur, hasDigit := 0, false
			for j < len(s) {
				d := s[j]
				if d >= '0' && d <= '9' {
					cur, hasDigit = cur*10+int(d-'0'), true
					j++
					continue
				}
				if d == ';' {
					params = append(params, cur)
					cur, hasDigit = 0, false
					j++
					continue
				}
				break
			}
			if hasDigit || len(params) > 0 {
				params = append(params, cur)
			}
			if j < len(s) && s[j] == 'm' {
				if len(params) == 0 || params[0] == 0 {
					colorSet = false
				} else if len(params) >= 5 && params[0] == 38 && params[1] == 2 {
					cr, cg, cb = clampByte(params[2]), clampByte(params[3]), clampByte(params[4])
					colorSet = true
				}
			}
			if j < len(s) {
				j++ // consume the final byte
			}
			i = j
			continue
		}

		if c == '\n' {
			row++
			col = 0
			i++
			continue
		}

		// One UTF-8 rune (fresco's glyphs are ≤3 bytes); place it as a cell.
		size := 1
		switch {
		case c >= 0xF0:
			size = 4
		case c >= 0xE0:
			size = 3
		case c >= 0xC0:
			size = 2
		}
		if i+size > len(s) {
			size = 1
		}
		ru := []rune(s[i : i+size])
		i += size
		if row < h && col < w && len(ru) > 0 {
			if colorSet && ru[0] != ' ' {
				grid[row][col] = cell{ch: ru[0], r: cr, g: cg, b: cb, lit: true}
			}
			// else: leave the default unlit space.
		}
		col++
	}
	return grid
}

// fieldCentroid is the luminance-weighted centre of mass of the lit field — the real
// galactic core, wherever fresco actually placed it, so the sparks shed from the light
// rather than from an assumed pane-centre. Falls back to the geometric centre if the
// field lit nothing (a degenerate frame).
func fieldCentroid(grid [][]cell) (cx, cy float64) {
	h := len(grid)
	w := 0
	if h > 0 {
		w = len(grid[0])
	}
	var sx, sy, sw float64
	for r := 0; r < h; r++ {
		for c := 0; c < w; c++ {
			bg := grid[r][c]
			if !bg.lit {
				continue
			}
			l := luma(rgb{float64(bg.r) / 255, float64(bg.g) / 255, float64(bg.b) / 255})
			sw += l
			sx += l * float64(c)
			sy += l * float64(r)
		}
	}
	if sw == 0 {
		return float64(w) / 2, float64(h) / 2
	}
	return sx / sw, sy / sw
}

// emberReach is how many lattice cells out emberLum must search: a spark's glow spans
// emberRadius, so a mote up to ceil(emberRadius) cells away can still reach the sample.
// Deriving it from the radius keeps the two in step if emberRadius is retuned.
var emberReach = int(math.Ceil(emberRadius))

// emberLum is the raw spark lattice — the granular foreground texture *before* the
// field gates it — at cell (col, row) and time t. The lattice is static in space; the
// whole sample coordinate drifts radially *outward* from the core (cx, cy) as t grows
// (t*emberRise along the outward unit vector), so the motes read as a slow shed from
// the centre. Pure in its arguments; all randomness enters through the integer hash.
// 0 means no mote here. The field coupling is applied by spark(), not here.
func emberLum(col, row int, t, cx, cy float64) float64 {
	dx := float64(col) - cx
	dy := float64(row) - cy
	// Pull the sample point inward as t grows, so the lattice pattern appears to flow
	// outward. At the exact core the direction is undefined; leave it unshifted.
	if r := math.Hypot(dx, dy); r > 1e-6 {
		s := t * emberRise / r
		dx -= dx * s
		dy -= dy * s
	}
	wx := (cx + dx) * emberScale
	wy := (cy + dy) * emberScale

	bx, by := math.Floor(wx), math.Floor(wy)
	best := 0.0
	for dj := -emberReach; dj <= emberReach; dj++ {
		for di := -emberReach; di <= emberReach; di++ {
			gx, gy := bx+float64(di), by+float64(dj)
			ix, iy := uint32(int32(gx)), uint32(int32(gy))
			if hash2(ix, iy, emberSeed) >= emberDensity {
				continue
			}
			sx := gx + hash2(ix, iy, emberSeed+1)
			sy := gy + hash2(ix, iy, emberSeed+2)
			d := math.Hypot(wx-sx, wy-sy)
			if d >= emberRadius {
				continue
			}
			base := 0.55 + 0.45*hash2(ix, iy, emberSeed+3)
			fall := 1 - d/emberRadius
			if l := base * fall * fall; l > best {
				best = l
			}
		}
	}
	return best
}

// fieldGate is the coupling made literal: it maps the galaxy luminance beneath a cell
// to how much of a spark can exist there. 0 below gateFloor (dark dust and the void
// shed nothing), rising to 1 at gateHi. Because this is exactly 0 where the field is
// dark, a spark can never appear off an arm — the property TestSparksTrackField pins.
func fieldGate(fieldLum float64) float64 {
	if fieldLum <= gateFloor {
		return 0
	}
	x := (fieldLum - gateFloor) / (gateHi - gateFloor)
	if x > 1 {
		x = 1
	}
	return math.Pow(x, gateGamma)
}

// spark is the final foreground intensity at (col, row): the raw lattice mote gated by
// the field luminance beneath it. This single function is the coupling — Frame paints
// it and TestSparksTrackField checks it, so removing the gate here is caught by the
// test. Zero wherever the galaxy is dark.
func spark(col, row int, t, fieldLum, cx, cy float64) float64 {
	g := fieldGate(fieldLum)
	if g == 0 {
		return 0
	}
	return emberLum(col, row, t, cx, cy) * g
}

// vig is the edge vignette: 1 at the centre, fading to 0 at every border, so the scene
// reads as a window onto something larger rather than a lit box. Applied to both layers
// so it ties them to one focal centre.
func vig(u, yn float64) float64 {
	e := math.Sin(math.Pi*u) * math.Sin(math.Pi*yn)
	if e <= 0 {
		return 0
	}
	return math.Pow(e, vigPow)
}

// luma is Rec. 709 relative luminance of a linearised-enough [0,1] colour — good enough
// to ask "how bright is the arm under this spark?" for the gate and the centroid.
func luma(c rgb) float64 { return 0.2126*c.r + 0.7152*c.g + 0.0722*c.b }

// Frame renders frame `tick` into exactly h lines of exactly w visible cells (or "" for
// a degenerate pane). Each lit cell is one truecolor foreground glyph; empty sky is a
// plain space. The background is fresco's galaxy, dimmed and its dust deepened; the
// foreground is the spark shed, gated to the arms and coloured by core proximity. Pure
// in (w, h, tick).
func Frame(w, h, tick int) string {
	if w <= 0 || h <= 0 {
		return ""
	}
	grid := parseField(w, h, tick)
	cx, cy := fieldCentroid(grid)
	t := float64(tick)
	W, H := float64(w), float64(h)

	// Farthest a cell can sit from the core, to normalise core proximity into 0..1.
	maxR := math.Hypot(math.Max(cx, W-cx), math.Max(cy, H-cy))
	if maxR < 1e-6 {
		maxR = 1
	}

	var b strings.Builder
	// A lit cell is at most ~22 bytes (\x1b[38;2;255;255;255m + glyph); each row adds a
	// 4-byte reset and a newline.
	b.Grow(w*h*22 + h*5)
	for r := 0; r < h; r++ {
		yn := (float64(r) + 0.5) / H
		var lr, lg, lb uint8
		colorSet := false
		for c := 0; c < w; c++ {
			u := (float64(c) + 0.5) / W
			bg := grid[r][c]

			var field rgb
			var fieldLum float64
			if bg.lit {
				field = rgb{float64(bg.r) / 255, float64(bg.g) / 255, float64(bg.b) / 255}
				fieldLum = luma(field)
			}

			em := spark(c, r, t, fieldLum, cx, cy)

			var out rgb
			glyph := ' '
			lit := false
			switch {
			case em > emberCut:
				e := (em - emberCut) / (1 - emberCut)
				// Core proximity: 1 at the galactic core, 0 at the far edge. It both
				// mixes the spark's colour warm→gold-white and boosts its brightness,
				// so the core reads as the furnace the sparks are shed from.
				coreProx := clamp01(1 - math.Hypot(float64(c)-cx, float64(r)-cy)/maxR)
				bright := clamp01(e * (1 + coreBoost*coreProx))
				ec := rgb{
					lerp(emberCool.r, emberHot.r, coreProx),
					lerp(emberCool.g, emberHot.g, coreProx),
					lerp(emberCool.b, emberHot.b, coreProx),
				}
				// Additive over the dimmed field, so the spark glows through it. The
				// core keeps a floor of brightness (ampFloor) so even a faint mote is a
				// visible point of light rather than a near-black dot.
				amp := ampFloor + (1-ampFloor)*bright
				dim := dimScale(fieldLum)
				out = rgb{
					field.r*dim + ec.r*amp,
					field.g*dim + ec.g*amp,
					field.b*dim + ec.b*amp,
				}
				glyph = emberGlyph(bright)
				lit = true
			case bg.lit:
				dim := dimScale(fieldLum)
				out = rgb{field.r * dim, field.g * dim, field.b * dim}
				glyph = bg.ch
				lit = true
			}

			// Focal vignette on the final composite.
			v := vig(u, yn)
			out = rgb{out.r * v, out.g * v, out.b * v}

			if lit {
				R, G, B := chan8(out.r), chan8(out.g), chan8(out.b)
				if !colorSet || R != lr || G != lg || B != lb {
					appendFG(&b, R, G, B)
					lr, lg, lb, colorSet = R, G, B, true
				}
				b.WriteRune(glyph)
			} else {
				if colorSet {
					b.WriteString("\x1b[0m")
					colorSet = false
				}
				b.WriteByte(' ')
			}
		}
		if colorSet {
			b.WriteString("\x1b[0m")
		}
		if r < h-1 {
			b.WriteByte('\n')
		}
	}
	return b.String()
}

// dimScale is how much the field is scaled when painted: frescoDim overall, plus a
// gamma that deepens the dark dust toward black (fieldGamma > 1) so the bright arms —
// and the sparks over them — read against negative space rather than a grey murk.
// Returned as a per-channel scale so a colour keeps its hue while losing luminance.
func dimScale(fieldLum float64) float64 {
	if fieldLum <= 0 {
		return 0
	}
	return frescoDim * math.Pow(fieldLum, fieldGamma-1)
}

// emberGlyph picks the foreground glyph for a spark of the given brightness — a small
// density ramp so a faint mote reads as a dot and a bright one as a star.
func emberGlyph(bright float64) rune {
	idx := int(clamp01(bright) * float64(len(emberGlyphs)))
	if idx >= len(emberGlyphs) {
		idx = len(emberGlyphs) - 1
	}
	return emberGlyphs[idx]
}

// appendFG writes a truecolor foreground SGR. Hand-rolled with strconv so the per-cell
// hot path carries no fmt reflection or allocation.
func appendFG(b *strings.Builder, r, g, bl uint8) {
	b.WriteString("\x1b[38;2;")
	writeChan(b, r)
	b.WriteByte(';')
	writeChan(b, g)
	b.WriteByte(';')
	writeChan(b, bl)
	b.WriteByte('m')
}

// writeChan appends one colour channel's decimal digits (0–255) to b.
func writeChan(b *strings.Builder, v uint8) {
	var s [3]byte
	b.Write(strconv.AppendUint(s[:0], uint64(v), 10))
}

// hash2 is the deterministic randomness source: a uint32 bit-mix of an integer lattice
// coordinate + seed, in [0,1). Large odd primes decorrelate the axes; unsigned
// multiplication wraps, which is what makes it a hash. (Same mixer as examples/nebula.)
func hash2(ix, iy, seed uint32) float64 {
	n := ix*374761393 + iy*668265263 + seed*2246822519
	n = (n ^ (n >> 13)) * 1274126177
	n ^= n >> 16
	return float64(n) / 4294967296.0
}

func lerp(a, b, t float64) float64 { return a + (b-a)*t }

func clamp01(x float64) float64 {
	switch {
	case x < 0:
		return 0
	case x > 1:
		return 1
	default:
		return x
	}
}

// clampByte narrows a parsed SGR channel to a byte, defending the parser against a
// malformed sequence without letting it panic.
func clampByte(v int) uint8 {
	switch {
	case v < 0:
		return 0
	case v > 255:
		return 255
	default:
		return uint8(v)
	}
}

func chan8(x float64) uint8 {
	switch {
	case x <= 0:
		return 0
	case x >= 1:
		return 255
	default:
		return uint8(x*255 + 0.5)
	}
}
